# Generated by Django 4.0.4 on 2022-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comment_content_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
