# Generated by Django 4.0.4 on 2022-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.FileField(upload_to='post_images/'),
        ),
    ]
